In [11]:
import pandas as pd
import tkinter as tk
from tkinter import filedialog
import xlsxwriter
import matplotlib.pyplot as plt

In [7]:
name = "SCWO.csv"
historicalYears = 8

In [22]:
df = pd.read_csv(name)
df.drop(['open', 'high','low','close','Volume','Volume MA'], axis=1, inplace=True)
count = 0
for i in df['time']:
        i = i[0:10]
        df.iloc[count, 0] = i
        count = count +1
df.set_index(df['time'])
print(df.shape)
for i in range(df.shape[0]-historicalYears):
    df.drop([df.index[0]], inplace = True) 
df2 = df
df2.set_index("time", inplace=True)
df2

(28, 90)

,Total revenue,COGS,Gross profit,Operating expenses (excl. COGS),Operating income,"Non-operating income, total",Pretax income,Equity in earnings,Taxes,Non-controlling/minority interest,...,Issuance/retirement of short term debt,Issuance/retirement of other debt,Total cash dividends paid,Common dividends paid,Preferred dividends paid,Free cash flow,Total non-current assets,Dividends per share - common stock primary issue,Number of employees,Mkt сap
time,,,,,,,,,,,,,,,,,,,,,
2016-01-04,587613.0,NaN,NaN,-616734.0,-61492.0,-62270.0,-123762.0,0.0,0.0,0.0,...,-147569.0,NaN,0.0,0.0,0.0,146750.0,131220.0,0.0,1.0,5.675312e+06
2017-01-03,852443.0,NaN,NaN,-384669.0,431328.0,-26975.0,404353.0,0.0,0.0,0.0,...,-275000.0,NaN,0.0,0.0,0.0,271550.0,94774.0,0.0,1.0,3.516923e+06
2018-01-02,190094.0,NaN,NaN,-850131.0,-680000.0,922.0,-679078.0,0.0,0.0,0.0,...,-150000.0,NaN,0.0,0.0,0.0,157150.0,74812.0,0.0,1.0,8.890000e+05
2019-01-02,24000.0,NaN,NaN,-430795.0,-412429.0,-102487.0,-514916.0,0.0,0.0,0.0,...,325000.0,NaN,0.0,0.0,0.0,-313450.0,0.0,0.0,1.0,5.143500e+06
2020-01-02,86570.0,-15152.0,71418.0,-74290.0,-2872.0,43209.0,40337.0,0.0,0.0,0.0,...,0.0,NaN,0.0,0.0,0.0,64760.0,678.0,0.0,1.0,2.175419e+08
2021-01-04,48100.0,-46050.0,2050.0,-2824196.0,-2822146.0,-342466.0,-3164608.0,0.0,0.0,0.0,...,0.0,NaN,0.0,0.0,NaN,-1842140.0,1063815.0,0.0,17.0,9.989817e+08
2022-01-03,3015521.0,-4391454.0,-1375933.0,-3380198.0,-4756131.0,66167.0,-4689967.0,0.0,0.0,0.0,...,0.0,NaN,0.0,0.0,0.0,-5093560.0,1193101.0,0.0,30.0,3.880895e+08
2023-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.461417e+07